---
title: "snRNAseq workflow: dimensionality reduction and clustering"
date: "`r format(Sys.time(), '%B %d, %Y')`"
geometry: margin=1in
fontfamily: mathpazo
fontsize: 11pt
params:
  rds_file: false
  cache_dir: false
output:
  html_document:
    keep_md: true
    code_folding: show
    toc: true
    toc_float: true
    toc_collapsed: true
    toc_depth: 4
    number_sections: true
    theme: lumen
---

```{r initialise, include = F}
# load packages
library(SCPA)
library(msigdbr)
library(magrittr)
library(dplyr)
library(ComplexHeatmap)
library(SummarizedExperiment)
library(circlize)
library(tidyverse)
library(monocle3)

# set ggplot presets
ggplot2::theme_set(ggplot2::theme_bw())
ggplot2::theme_update(legend.text = ggplot2::element_text(size = 7))
ditto_colours <- list(ggplot2::scale_fill_manual(values = dittoSeq::dittoColors(), na.value = "white"),
                      ggplot2::scale_colour_manual(values = dittoSeq::dittoColors(), na.value = "white"))
umap_void_theme <-
  ggplot2::theme(axis.text = ggplot2::element_blank(),
                 axis.title = ggplot2::element_blank(),
                 axis.ticks = ggplot2::element_blank(),
                 legend.position = "none",
                 plot.margin = ggplot2::unit(c(2,2,2,2), "pt"))

# chunk setup
knitr::opts_chunk$set(fig.align = "center",
                      dpi = 300,
                      cache.path = params$cache_dir)

# functions
fix_pathway_names <- function(pathway_names) {
  pathway_names %>% tolower() %>% gsub("\\_", " ", .) %>% gsub("hallmark ", "", .)
}
plot_my_heatmap <- function(p_dat_in, col, stat = "qval") {
  p_dat_in %>%
    select(Pathway, name = matches(col), value = matches(stat)) %>%
    mutate(Pathway = fix_pathway_names(Pathway)) %>%
    pivot_wider() %>%
    column_to_rownames("Pathway") %>%
    as.matrix() %>%
    Heatmap(name = stat,
            border = T,
            show_row_dend = F,
            show_column_dend = T,
            row_names_gp = grid::gpar(fontsize = 8))
}
plot_my_enrichment <- function(p_dat_in, top_n = 5) {
  p_dat <-
    p_dat_in %>%
    mutate(Pathway = Pathway %>% fix_pathway_names(),
           color = case_when(FC > 5 & adjPval < 0.01 ~ '#6dbf88',
                             FC < 5 & FC > -5 & adjPval < 0.01 ~ '#84b0f0',
                             FC < -5 & adjPval < 0.01 ~ 'mediumseagreen',
                             FC < 5 & FC > -5 & adjPval > 0.01 ~ 'black'))

  ggplot(p_dat, aes(-FC, qval)) +
    geom_vline(xintercept = c(-5, 5), linetype = "dashed", col = 'black', lwd = 0.3) +
    geom_point(cex = 2.6, shape = 21, fill = p_dat$color, stroke = 0.3) +
    ggrepel::geom_text_repel(data = p_dat %>% slice_max(abs(FC), n = top_n), aes(label = Pathway),
                             size = 7, min.segment.length = 0, nudge_x = 10) +
    xlab("Enrichment") +
    ylab("Qval") +
    theme(panel.background = element_blank(),
          panel.border = element_rect(fill = NA),
          aspect.ratio = 1) +
    ggplot2::theme(text = ggplot2::element_text(size = 20))
}
```

# Pathway analysis

```{r pathway_analysis, echo = F}
# load seu 
seu <- readRDS(params$rds_file)

# find markers of pre- vs post-treatment
tests <- list(timepoint = "post", sample_site = "lymph_node")
degs <-
  tests %>%
  names() %>%
  purrr::map(
    function(test) {
      print(test)
      seu %>%
        Seurat::FindMarkers(
          ident.1 = colnames(seu[, seu@meta.data[, test] == tests[[test]]]), 
          test.use = "MAST"
        ) %>%
        tibble::as_tibble(rownames = "gene")
    }
  ) %>%
  setNames(unlist(tests)) %>%
  dplyr::bind_rows(.id = "test")

degs %>%
  dplyr::mutate(
    abs_avg_log2FC = abs(avg_log2FC),
    direction = ifelse(avg_log2FC > 0, "upregulated", "downregulated"),
    label = gene,
    gene = tidytext::reorder_within(x = gene, within = test, by = abs_avg_log2FC),
    neglog10_p_val_adj = -log10(p_val_adj)
  ) %>%
  dplyr::group_by(test, direction) %>%
  dplyr::filter(p_val_adj < 0.05) %>%
  dplyr::top_n(10, avg_log2FC) %>%
  ggplot2::ggplot(ggplot2::aes(
    x = gene, y = abs_avg_log2FC, fill = neglog10_p_val_adj, label = label)) +
  ggplot2::geom_col() +
  ggplot2::geom_text(ggplot2::aes(hjust = -0.1)) +
  ggplot2::facet_wrap(test ~ direction, scales = "free") +
  ggplot2::scale_fill_continuous() +
  ggplot2::coord_flip() +
  ggplot2::theme_classic() +
  ggplot2::theme(axis.text.y = ggplot2::element_blank(),
                 axis.ticks.y = ggplot2::element_blank()) + 
  ggplot2::scale_y_continuous(expand = ggplot2::expansion(mult = c(0, 0.5)))

# convert to cds
cds <- SeuratWrappers::as.cell_data_set(seu, assay = "RNA")
SummarizedExperiment::rowData(cds)$gene_short_name <- 
  row.names(SummarizedExperiment::rowData(cds))

# preprocess
cds <- preprocess_cds(cds, num_dim = 30)
cds <- reduce_dimension(cds)

# get hallmark pathways
pathways <-
  msigdbr(species = "Homo sapiens", category = "H") %>%
  format_pathways()

# initiate list
scpa_out <- list()

# compare pathways between tumour vs normal
scpa_out[["normal_vs_malignant"]] <-
  compare_sce(cds,
              group1 = "label.infercnv",
              group1_population = c("Epithelial_cells", "Malignant_cells"),
              pathways = pathways)
scpa_out[["pre_vs_post"]] <-
  compare_sce(cds,
              group1 = "timepoint",
              group1_population = c("pre", "post"),
              pathways = pathways)
scpa_out[["both"]] <-
  compare_sce(cds,
              group1 = "label.infercnv",
              group1_population = c("Epithelial_cells", "Malignant_cells"),
              group2 = "timepoint",
              group2_population = c("post", "pre"),
              pathways = pathways)
plot_my_enrichment(scpa_out$normal_vs_malignant)
plot_my_enrichment(scpa_out$pre_vs_post)
```

```{r dea_norm_vs_malig}
find_markers <- function(seu, col, group.1, group.2) {
  seu %>% 
    Seurat::FindMarkers(
      ident.1 = colnames(seu[, seu@meta.data[, col] == group.1]),
      ident.2 = colnames(seu[, seu@meta.data[, col] == group.2]),
      test.use = "MAST"
    ) %>%
    tibble::as_tibble(rownames = "gene") %>%
    dplyr::filter(p_val_adj < 0.05) %>%
    dplyr::mutate(direction = ifelse(avg_log2FC > 0, group.1, group.2),
                  group = ifelse(avg_log2FC > 0, 1, 2)) %>%
    dplyr::group_by(direction) %>%
    dplyr::mutate(rank = rank(-abs(avg_log2FC))) 
}
plot_markers <- function(markers, top_n = 10) {
  p_dat <-
    markers %>%
    dplyr::filter(rank <= top_n) %>%
    dplyr::group_by(direction) %>%
    dplyr::mutate(rank = rank(-abs(avg_log2FC))) %>%
    dplyr::filter(rank <= top_n)
  p_dat %>%
    ggplot(aes(x = -rank, y = avg_log2FC, 
               fill = direction, alpha = -log10(p_val_adj),
               label = gene)) +
    geom_bar(stat = "identity") +
    geom_text(hjust = ifelse(p_dat$group == 2, 1.1, -0.1),
              alpha = 1,
              size = 6) +
    scale_y_continuous(labels = abs, limits = max(abs(p_dat$avg_log2FC)) * c(-1,1) * 1.3) +
    scale_fill_manual(values=as.vector(c("#d23f67","#3179de"))) +
    labs(x = "", y = "", fill="") +
    theme_minimal() +   
    coord_flip() +
    theme( 
      panel.grid.major = element_blank(), 
      panel.grid.minor = element_blank(),
      axis.text.x = element_text(size=20), 
      axis.text.y = element_blank(),
      strip.text.x=element_text(size=24),
      legend.position="bottom",
      legend.text=element_text(size=20)
    )
}

markers <- list()
markers[["malignant_vs_epithelial"]] <-
  find_markers(seu, "label.infercnv", "Malignant_cells", "Epithelial_cells")
markers[["lymph_node_vs_tumour"]] <-
  find_markers(seu, "sample_site", "lymph_node", "tumour")
markers[["lymph_node_malignant_vs_tumour_malignant"]] <-
  find_markers(seu[, seu$label.infercnv == "Malignant_cells"],
               "sample_site", "lymph_node", "tumour")
markers[["post_malignant_vs_pre_malignant"]] <-
  find_markers(seu[, seu$label.infercnv == "Malignant_cells"],
               "timepoint", "post", "pre")
celltype_markers <-
  Seurat::FindMarkers(seu, group.by = "label.infercnv")

# find markers for every celltype
seu <- Seurat::ScaleData(seu)
Seurat::Idents(seu) <- seu$label.infercnv
celltype_markers <- 
  Seurat::FindAllMarkers(seu, test.use = "MAST") %>% 
  tibble::as_tibble()
celltype_markers %>%
  dplyr::filter(avg_log2FC > 0, p_val < 0.05) %>%
  dplyr::group_by(cluster) %>%
  dplyr::slice_max(order_by = avg_log2FC, n = 5)

# do heatmap
seu$label_n <-
  tibble::tibble(label = seu$label.infercnv) %>% 
  dplyr::group_by(label) %>%
  dplyr::mutate(n = dplyr::n()) %>% 
  dplyr::pull(n)
top_celltype_markers <-
  celltype_markers %>%
  dplyr::group_by(cluster) %>%
  dplyr::top_n(n = 3, wt = avg_log2FC) 
dittoSeq::dittoHeatmap(
  seu, genes = unique(top_celltype_markers$gene),
  annot.by = "label.infercnv", order.by = "label_n")

# cluster markers
Seurat::Idents(seu) <- seu$SCT_snn_res.0.1 
cluster_markers <-
  Seurat::FindAllMarkers(seu, test.use = "MAST")
```
