---
title: "snRNAseq workflow: dimensionality reduction and clustering"
date: "`r format(Sys.time(), '%B %d, %Y')`"
geometry: margin=1in
fontfamily: mathpazo
fontsize: 11pt
params:
  cache_dir: false
output:
  html_document:
    keep_md: true
    code_folding: show
    toc: true
    toc_float: true
    toc_collapsed: true
    toc_depth: 4
    number_sections: true
    theme: lumen
---

```{r initialise, include = F}
# load packages
library(SCPA)
library(msigdbr)
library(magrittr)
library(dplyr)
library(SummarizedExperiment)
library(tidyverse)
library(monocle3)

# set ggplot presets
ggplot2::theme_set(ggplot2::theme_bw())
ggplot2::theme_update(legend.text = ggplot2::element_text(size = 7))
ditto_colours <- list(ggplot2::scale_fill_manual(values = dittoSeq::dittoColors(), na.value = "white"),
                      ggplot2::scale_colour_manual(values = dittoSeq::dittoColors(), na.value = "white"))
umap_void_theme <-
  ggplot2::theme(axis.text = ggplot2::element_blank(),
                 axis.title = ggplot2::element_blank(),
                 axis.ticks = ggplot2::element_blank(),
                 legend.position = "none",
                 plot.margin = ggplot2::unit(c(2,2,2,2), "pt"))

# chunk setup
knitr::opts_chunk$set(fig.align = "center",
                      dpi = 300,
                      cache.path = params$cache_dir)

# functions
fix_pathway_names <- function(pathway_names) {
  pathway_names %>% tolower() %>% gsub("\\_", " ", .) %>% gsub("hallmark ", "", .)
}
plot_my_heatmap <- function(p_dat_in, col, stat = "qval") {
  p_dat_in %>%
    select(Pathway, name = matches(col), value = matches(stat)) %>%
    mutate(Pathway = fix_pathway_names(Pathway)) %>%
    pivot_wider() %>%
    column_to_rownames("Pathway") %>%
    as.matrix() %>%
    Heatmap(name = stat,
            border = T,
            show_row_dend = F,
            show_column_dend = T,
            row_names_gp = grid::gpar(fontsize = 8))
}
plot_my_enrichment <- function(p_dat_in, top_n = 5) {
  p_dat <-
    p_dat_in %>%
    mutate(Pathway = Pathway %>% fix_pathway_names(),
           color = case_when(FC > 5 & adjPval < 0.01 ~ '#6dbf88',
                             FC < 5 & FC > -5 & adjPval < 0.01 ~ '#84b0f0',
                             FC < -5 & adjPval < 0.01 ~ 'mediumseagreen',
                             FC < 5 & FC > -5 & adjPval > 0.01 ~ 'black'))

  ggplot(p_dat, aes(-FC, qval)) +
    geom_vline(xintercept = c(-5, 5), linetype = "dashed", col = 'black', lwd = 0.3) +
    geom_point(cex = 2.6, shape = 21, fill = p_dat$color, stroke = 0.3) +
    ggrepel::geom_text_repel(data = p_dat %>% filter(rank(FC, ties.method = "min") <= 5 | rank(-qval, ties.method = "min") <= 5), aes(label = Pathway),
                             size = 4, min.segment.length = 0, nudge_x = 10) +
    xlab("Enrichment") +
    ylab("Qval") +
    theme(panel.background = element_blank(),
          panel.border = element_rect(fill = NA),
          aspect.ratio = 1) +
    ggplot2::theme(text = ggplot2::element_text(size = 20))
}
```

# Pathway analysis

```{r load_seu}
# load seu 
seu <- readRDS("seu.rds")
```

```{r annotate_malig}
# define malignancy by aneuploidy status
aneuploid_cells <- 
  cnv_files %>%
  purrr::map(function(cnv_file_i) {
    sample_i <- gsub("/.*", "", cnv_file_i)
    readr::read_tsv(paste0(params$infercnv_cache_dir, cnv_file_i)) %>%
      dplyr::mutate(sample = sample_i)
  }) %>%
  dplyr::bind_rows() %>%
  dplyr::group_by(sample, cell_group_name) %>%
  dplyr::summarise(aneuploid = any(c(1, 3) %in% state)) %>%
  dplyr::filter(aneuploid)
malignant_cells <-
  aneuploid_cells %>%
  dplyr::filter(cell_group_name %in% colnames(seu[, seu$label.reduced == "Epithelial_cells"]))

# save
saveRDS(aneuploid_cells, "aneuploid_cells.rds")
saveRDS(malignant_cells, "malignant_cells.rds")

# exclude epithelial samples in samples for which infercnv run was unsuccessful 
# (malignant annotations not present)
seu <- seu[, (seu$sample %in% gsub("/.*", "", cnv_files) |
             seu$label.reduced != "Epithelial_cells")]

# add aneuploid and malignant labels 
seu$aneuploid <- 0
seu@meta.data[aneuploid_cells$cell_group_name, "aneuploid"] <- 1
seu$label.infercnv <- seu$label.reduced
seu@meta.data[malignant_cells$cell_group_name, "label.infercnv"] <- "Malignant_cells"
```

```{r find_markers}
degs <- xfun::cache_rds({
  degs <- list()

  if (all(c("Malignant_cells", "Epithelial_cells") %in% seu$label.infercnv)) {
    # find markers of malignant vs epithelial
    degs[["malignant_vs_epithelial"]] <-
       find_markers(seu, "label.infercnv", "Malignant_cells", "Epithelial_cells")
  }
  
  # if (all(c("post", "pre") %in% seu$timepoint)) {
  #   if (ncol(seu[, seu$label.infercnv == "Malignant_cells"]) > 0) {
  #     # find markers of malignant post vs malignant pre
  #     degs[["malignant_post_vs_malignant_pre"]] <-
  #       find_markers(seu[, seu$label.infercnv == "Malignant_cells"], 
  #                    "timepoint", "post", "pre")
  #   }
  #   
  #   # find markers of post vs pre
  #   degs[["post_vs_pre"]] <-
  #     find_markers(seu, "timepoint", "post", "pre")
  # }
  
  # return
  degs
  
}, file = "degs.rds")

# save
saveRDS(degs, "degs.rds")

# # plot
# plot_markers(degs$malignant_vs_epithelial, 20)
# plot_markers(degs$malignant_post_vs_malignant_pre, 20)
# plot_markers(degs$post_vs_pre, 20)
```

# Pathway analysis

```{r pathway_analysis, eval = F}
# convert to cds
cds <- SeuratWrappers::as.cell_data_set(seu, assay = "RNA")
SummarizedExperiment::rowData(cds)$gene_short_name <- 
  row.names(SummarizedExperiment::rowData(cds))

# preprocess
cds <- preprocess_cds(cds, num_dim = 30)
cds <- reduce_dimension(cds)

# get hallmark pathways
pathways <- xfun::cache_rds({
  pathways <-
    msigdbr(species = "Homo sapiens", category = "H") %>%
    format_pathways()
  pathways
}, file = "pathways.rds")

# compare pathways between tumour vs normal
scpa_out <- xfun::cache_rds({
  scpa_out <- list()
  scpa_out[["malignant_vs_epithelial"]] <-
    compare_sce(cds,
                group1 = "label.infercnv",
                group1_population = c("Malignant_cells", "Epithelial_cells"),
                pathways = pathways)
  # scpa_out[["malignant_post_vs_malignant_pre"]] <-
  #   compare_sce(cds[, cds@colData$label.infercnv == "Malignant_cells"],
  #               group1 = "timepoint",
  #               group1_population = c("pre", "post"),
  #               pathways = pathways)
  # scpa_out[["post_vs_pre"]] <-
  #   compare_sce(cds,
  #               group1 = "timepoint",
  #               group1_population = c("pre", "post"),
  #               pathways = pathways)
  scpa_out
}, file = "scpa.rds")

# save 
saveRDS(scpa_out, "scpa.rds")

# # plot
# plot_my_enrichment(scpa_out$malignant_vs_epithelial)
# plot_my_enrichment(scpa_out$malignant_post_vs_malignant_pre)
# plot_my_enrichment(scpa_out$post_vs_pre)
```

