#PBS -l walltime=72:00:00
#PBS -l select=1:ncpus=1:mem=24gb
#PBS -o /rds/general/user/art4017/home/snRNAseq_workflow/run/run_by_patient.out
#PBS -e /rds/general/user/art4017/home/snRNAseq_workflow/run/run_by_patient.err

cd /rds/general/user/art4017/home/snRNAseq_workflow/
> run/run_by_patient.out ; > run/run_by_patient.err

. ~/.bashrc
conda activate nfcore
module load gcc/8.2.0
NXF_OPTS='-Xms1g -Xmx4g'

nextflow run . \
  -c config/oesophageal_10X.config \
  -c config/imperial.config \
  -profile imperial \
  -with-singularity /rds/general/user/art4017/home/nf-core/scflow/work/singularity/snRNAseq_workflow2.img \
  --input.patient_manifest input/oesophageal_10X/patient_manifest.tsv \
  --input.run_all false \
  --output.dir output/oesophageal_10X/by_patient/ \
  -w work_by_patient/
