#PBS -l walltime=48:00:00
#PBS -l select=1:ncpus=1:mem=24gb
#PBS -o /rds/general/user/art4017/home/snRNAseq_workflow/run/test.out
#PBS -e /rds/general/user/art4017/home/snRNAseq_workflow/run/test.err

cd /rds/general/user/art4017/home/snRNAseq_workflow/
> run/run.out ; > run/run.err

. ~/.bashrc
conda activate nfcore
module load gcc/8.2.0
NXF_OPTS='-Xms1g -Xmx4g'

nextflow run . \
  -c config/oesophageal_10X.config \
  -c config/imperial.config \
  -profile imperial \
  -with-singularity /rds/general/user/art4017/home/nf-core/scflow/work/singularity/snRNAseq_workflow2.img \
  --input.manifest_file input/oesophageal_10X/sample_manifest_by_patient_without_organoids/K.tsv \
  --output.dir output/oesophageal_10X/by_patient_without_organoids/K/ \
  -w work_by_patient/K/ \
  -resume